package Vista;

import Controlador.ControladorMenu;
import Modelo.ModeloMenu;

/**
 *
 * @author GrupoNo.4
 */
public class VistaPrincipal extends javax.swing.JFrame {

    /**
     * Creates new form VistaGestionInventario
     */
    public VistaPrincipal() {
        initComponents();
        setLocationRelativeTo(null);
        Modelo.ModeloMenu modelo = new ModeloMenu(this);
        
        Controlador.ControladorMenu controlador = new ControladorMenu(modelo);
        setControlador(controlador);
//        Controlador.ControladorMenu controlador = new ControladorMenu(modelo);
//        setControlador(controlador);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Fondo = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        btnIngresarUsuario = new javax.swing.JPanel();
        btnInformes = new javax.swing.JPanel();
        btnActualizacionProductos = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        btnIngresoProductos = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        btnVenta = new javax.swing.JPanel();
        fondoMenu = new javax.swing.JLabel();
        contenedor = new javax.swing.JPanel();
        contenedor2 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setResizable(false);

        Fondo.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Menú");
        Fondo.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 10, -1, -1));

        btnIngresarUsuario.setBackground(new java.awt.Color(102, 102, 0));

        javax.swing.GroupLayout btnIngresarUsuarioLayout = new javax.swing.GroupLayout(btnIngresarUsuario);
        btnIngresarUsuario.setLayout(btnIngresarUsuarioLayout);
        btnIngresarUsuarioLayout.setHorizontalGroup(
            btnIngresarUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );
        btnIngresarUsuarioLayout.setVerticalGroup(
            btnIngresarUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 40, Short.MAX_VALUE)
        );

        Fondo.add(btnIngresarUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 350, 300, 40));

        btnInformes.setBackground(new java.awt.Color(153, 204, 255));

        javax.swing.GroupLayout btnInformesLayout = new javax.swing.GroupLayout(btnInformes);
        btnInformes.setLayout(btnInformesLayout);
        btnInformesLayout.setHorizontalGroup(
            btnInformesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );
        btnInformesLayout.setVerticalGroup(
            btnInformesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 40, Short.MAX_VALUE)
        );

        Fondo.add(btnInformes, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 310, 300, 40));

        btnActualizacionProductos.setBackground(new java.awt.Color(102, 102, 0));
        btnActualizacionProductos.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setText("Actualizar Producto");
        btnActualizacionProductos.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 300, 40));

        Fondo.add(btnActualizacionProductos, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 270, 300, 40));

        btnIngresoProductos.setBackground(new java.awt.Color(153, 204, 255));
        btnIngresoProductos.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1.setText("Ingresar Producto");
        btnIngresoProductos.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 300, 40));

        Fondo.add(btnIngresoProductos, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 230, 300, 40));

        btnVenta.setBackground(new java.awt.Color(102, 102, 0));

        javax.swing.GroupLayout btnVentaLayout = new javax.swing.GroupLayout(btnVenta);
        btnVenta.setLayout(btnVentaLayout);
        btnVentaLayout.setHorizontalGroup(
            btnVentaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );
        btnVentaLayout.setVerticalGroup(
            btnVentaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 40, Short.MAX_VALUE)
        );

        Fondo.add(btnVenta, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 190, 300, 40));

        fondoMenu.setBackground(new java.awt.Color(51, 51, 51));
        fondoMenu.setOpaque(true);
        fondoMenu.setPreferredSize(new java.awt.Dimension(300, 720));
        Fondo.add(fondoMenu, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        contenedor.setBackground(new java.awt.Color(102, 102, 102));

        javax.swing.GroupLayout contenedorLayout = new javax.swing.GroupLayout(contenedor);
        contenedor.setLayout(contenedorLayout);
        contenedorLayout.setHorizontalGroup(
            contenedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 980, Short.MAX_VALUE)
        );
        contenedorLayout.setVerticalGroup(
            contenedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 720, Short.MAX_VALUE)
        );

        Fondo.add(contenedor, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 0, 980, 720));

        javax.swing.GroupLayout contenedor2Layout = new javax.swing.GroupLayout(contenedor2);
        contenedor2.setLayout(contenedor2Layout);
        contenedor2Layout.setHorizontalGroup(
            contenedor2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );
        contenedor2Layout.setVerticalGroup(
            contenedor2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 720, Short.MAX_VALUE)
        );

        Fondo.add(contenedor2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 300, 720));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Fondo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Fondo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VistaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VistaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VistaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VistaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VistaPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Fondo;
    public javax.swing.JPanel btnActualizacionProductos;
    private javax.swing.JPanel btnInformes;
    private javax.swing.JPanel btnIngresarUsuario;
    public javax.swing.JPanel btnIngresoProductos;
    private javax.swing.JPanel btnVenta;
    public javax.swing.JPanel contenedor;
    public javax.swing.JPanel contenedor2;
    private javax.swing.JLabel fondoMenu;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    // End of variables declaration//GEN-END:variables

    public void setControlador(ControladorMenu controlador){
//        btnIngresoProductos.addActionListener(controlador);
//        btnVenta.addActionListener(controlador);
//        btnActualizacionProductos.addActionListener(controlador);
        this.addWindowListener(controlador);
        btnIngresoProductos.addMouseListener(controlador);
        btnActualizacionProductos.addMouseListener(controlador);
        
    }
    
}
