package Vista;
//COMENTARIO ADICIONAL MARIO PAZ
/**
 *
 * @author GrupoNo.4
 */

import Controlador.ControladorLogin;
import Modelo.ModeloLogin;
import javax.swing.ImageIcon;


public class VistaLogin extends javax.swing.JFrame {
    
    public VistaLogin() {
        initComponents();
        setIconImage(new ImageIcon(getClass().getResource("/ramyrem.png")).getImage());
        
        
        setLocationRelativeTo(null);
        Modelo.ModeloLogin modelo = new ModeloLogin(this);
        Controlador.ControladorLogin controlador = new ControladorLogin(modelo);
        setControlador(controlador);
        controlador.abrirMenu();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        FondoPanelInicio = new javax.swing.JPanel();
        letTituloVentana = new javax.swing.JLabel();
        letContraseña = new javax.swing.JLabel();
        letUsuario = new javax.swing.JLabel();
        txtNombreUsuario = new javax.swing.JTextField();
        txtContraseñaUsuario = new javax.swing.JPasswordField();
        jSeparator2 = new javax.swing.JSeparator();
        jSeparator1 = new javax.swing.JSeparator();
        btnIngresoMenu = new javax.swing.JPanel();
        letBotonIniciarSesion = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        setSize(new java.awt.Dimension(1280, 720));

        FondoPanelInicio.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        letTituloVentana.setFont(new java.awt.Font("Corbel Light", 0, 30)); // NOI18N
        letTituloVentana.setForeground(new java.awt.Color(255, 255, 255));
        letTituloVentana.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        letTituloVentana.setText("INICIO DE SESIÓN");
        FondoPanelInicio.add(letTituloVentana, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 300, 60));

        letContraseña.setBackground(new java.awt.Color(255, 255, 255));
        letContraseña.setFont(new java.awt.Font("Corbel Light", 0, 14)); // NOI18N
        letContraseña.setForeground(new java.awt.Color(255, 255, 255));
        letContraseña.setText("CONTRASEÑA");
        FondoPanelInicio.add(letContraseña, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 240, 250, -1));

        letUsuario.setBackground(new java.awt.Color(255, 255, 255));
        letUsuario.setFont(new java.awt.Font("Corbel Light", 0, 14)); // NOI18N
        letUsuario.setForeground(new java.awt.Color(255, 255, 255));
        letUsuario.setText("USUARIO");
        FondoPanelInicio.add(letUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 150, 250, -1));

        txtNombreUsuario.setBackground(new java.awt.Color(51, 51, 51));
        txtNombreUsuario.setForeground(new java.awt.Color(255, 255, 255));
        txtNombreUsuario.setBorder(null);
        FondoPanelInicio.add(txtNombreUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 170, 240, -1));

        txtContraseñaUsuario.setBackground(new java.awt.Color(51, 51, 51));
        txtContraseñaUsuario.setForeground(new java.awt.Color(255, 255, 255));
        txtContraseñaUsuario.setBorder(null);
        FondoPanelInicio.add(txtContraseñaUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 260, 240, -1));

        jSeparator2.setBackground(new java.awt.Color(255, 255, 255));
        FondoPanelInicio.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 280, 240, 10));

        jSeparator1.setBackground(new java.awt.Color(255, 255, 255));
        FondoPanelInicio.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 190, 240, 10));

        btnIngresoMenu.setBackground(new java.awt.Color(102, 102, 102));
        btnIngresoMenu.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnIngresoMenu.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        letBotonIniciarSesion.setFont(new java.awt.Font("Corbel Light", 0, 14)); // NOI18N
        letBotonIniciarSesion.setForeground(new java.awt.Color(255, 255, 255));
        letBotonIniciarSesion.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        letBotonIniciarSesion.setText("INICIAR SESIÓN");
        btnIngresoMenu.add(letBotonIniciarSesion, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 10, 130, 25));

        FondoPanelInicio.add(btnIngresoMenu, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 300, 130, 40));

        jLabel1.setBackground(new java.awt.Color(79, 109, 122));
        jLabel1.setOpaque(true);
        jLabel1.setPreferredSize(new java.awt.Dimension(1280, 720));
        FondoPanelInicio.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 0, 980, -1));

        jLabel2.setBackground(new java.awt.Color(51, 51, 51));
        jLabel2.setOpaque(true);
        FondoPanelInicio.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 300, 720));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(FondoPanelInicio, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(FondoPanelInicio, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VistaLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VistaLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VistaLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VistaLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VistaLogin().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel FondoPanelInicio;
    public javax.swing.JPanel btnIngresoMenu;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JLabel letBotonIniciarSesion;
    private javax.swing.JLabel letContraseña;
    private javax.swing.JLabel letTituloVentana;
    private javax.swing.JLabel letUsuario;
    private javax.swing.JPasswordField txtContraseñaUsuario;
    private javax.swing.JTextField txtNombreUsuario;
    // End of variables declaration//GEN-END:variables
    
    public void setControlador(ControladorLogin controlador){
        
        this.addWindowListener(controlador);
        btnIngresoMenu.addMouseListener(controlador);
        
        
    }

}
