package Vista;

import Controlador.ControladorMenu;
import Modelo.ModeloMenu;

/**
 *
 * @author GrupoNo.4
 */
public class VistaPrincipal extends javax.swing.JFrame {

    /**
     * Creates new form VistaGestionInventario
     */
    public VistaPrincipal() {
        initComponents();
        setLocationRelativeTo(null);
        Modelo.ModeloMenu modelo = new ModeloMenu(this);
        
        Controlador.ControladorMenu controlador = new ControladorMenu(modelo);
        setControlador(controlador);
//        Controlador.ControladorMenu controlador = new ControladorMenu(modelo);
//        setControlador(controlador);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Fondo = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        btnCerrarSesion = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        btnAgregarUsuario = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        btnInformes = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        btnActualizacionProductos = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        btnIngresoProductos = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        btnVenta = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        btnAgregarEmpleado = new javax.swing.JPanel();
        letAgregarEmpleado = new javax.swing.JLabel();
        fondoMenu = new javax.swing.JLabel();
        contenedor = new javax.swing.JPanel();
        contenedor2 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setResizable(false);

        Fondo.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Corbel Light", 0, 30)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("MENÚ");
        Fondo.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 300, 60));

        btnCerrarSesion.setBackground(new java.awt.Color(51, 51, 51));
        btnCerrarSesion.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnCerrarSesion.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel7.setFont(new java.awt.Font("Corbel Light", 0, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setText("CERRAR SESIÓN");
        btnCerrarSesion.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 300, 40));

        Fondo.add(btnCerrarSesion, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 680, 300, 40));

        btnAgregarUsuario.setBackground(new java.awt.Color(51, 51, 51));
        btnAgregarUsuario.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnAgregarUsuario.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel5.setFont(new java.awt.Font("Corbel Light", 0, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("AGREGAR USUARIO");
        jLabel5.setBorder(javax.swing.BorderFactory.createEmptyBorder(20, 20, 20, 20));
        btnAgregarUsuario.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 300, 40));

        Fondo.add(btnAgregarUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 350, 300, 40));

        btnInformes.setBackground(new java.awt.Color(51, 51, 51));
        btnInformes.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnInformes.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel4.setFont(new java.awt.Font("Corbel Light", 0, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("REALIZAR INFORME");
        jLabel4.setBorder(javax.swing.BorderFactory.createEmptyBorder(20, 20, 20, 20));
        btnInformes.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 300, 40));

        Fondo.add(btnInformes, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 310, 300, 40));

        btnActualizacionProductos.setBackground(new java.awt.Color(51, 51, 51));
        btnActualizacionProductos.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnActualizacionProductos.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setFont(new java.awt.Font("Corbel Light", 0, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("ACTUALIZAR PRODUCTO");
        jLabel3.setBorder(javax.swing.BorderFactory.createEmptyBorder(20, 20, 20, 20));
        btnActualizacionProductos.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 300, 40));

        Fondo.add(btnActualizacionProductos, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 270, 300, 40));

        btnIngresoProductos.setBackground(new java.awt.Color(51, 51, 51));
        btnIngresoProductos.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnIngresoProductos.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Corbel Light", 0, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("INGRESAR PRODUCTO");
        jLabel1.setBorder(javax.swing.BorderFactory.createEmptyBorder(20, 20, 20, 20));
        btnIngresoProductos.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 300, 40));

        Fondo.add(btnIngresoProductos, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 230, 300, 40));

        btnVenta.setBackground(new java.awt.Color(51, 51, 51));
        btnVenta.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnVenta.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel6.setFont(new java.awt.Font("Corbel Light", 0, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("REALIZAR UNA VENTA");
        jLabel6.setBorder(javax.swing.BorderFactory.createEmptyBorder(20, 20, 20, 20));
        btnVenta.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 300, 40));

        Fondo.add(btnVenta, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 190, 300, 40));

        btnAgregarEmpleado.setBackground(new java.awt.Color(51, 51, 51));
        btnAgregarEmpleado.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnAgregarEmpleado.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        letAgregarEmpleado.setFont(new java.awt.Font("Corbel Light", 0, 18)); // NOI18N
        letAgregarEmpleado.setForeground(new java.awt.Color(255, 255, 255));
        letAgregarEmpleado.setText("AGREGAR EMPLEADO");
        letAgregarEmpleado.setBorder(javax.swing.BorderFactory.createEmptyBorder(20, 20, 20, 20));
        btnAgregarEmpleado.add(letAgregarEmpleado, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 300, 40));

        Fondo.add(btnAgregarEmpleado, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 390, 300, 40));

        fondoMenu.setBackground(new java.awt.Color(51, 51, 51));
        fondoMenu.setOpaque(true);
        fondoMenu.setPreferredSize(new java.awt.Dimension(300, 720));
        Fondo.add(fondoMenu, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        contenedor.setBackground(new java.awt.Color(79, 109, 122));

        javax.swing.GroupLayout contenedorLayout = new javax.swing.GroupLayout(contenedor);
        contenedor.setLayout(contenedorLayout);
        contenedorLayout.setHorizontalGroup(
            contenedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 980, Short.MAX_VALUE)
        );
        contenedorLayout.setVerticalGroup(
            contenedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 720, Short.MAX_VALUE)
        );

        Fondo.add(contenedor, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 0, 980, 720));

        javax.swing.GroupLayout contenedor2Layout = new javax.swing.GroupLayout(contenedor2);
        contenedor2.setLayout(contenedor2Layout);
        contenedor2Layout.setHorizontalGroup(
            contenedor2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );
        contenedor2Layout.setVerticalGroup(
            contenedor2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 720, Short.MAX_VALUE)
        );

        Fondo.add(contenedor2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 300, 720));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Fondo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Fondo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VistaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VistaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VistaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VistaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VistaPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Fondo;
    public javax.swing.JPanel btnActualizacionProductos;
    public javax.swing.JPanel btnAgregarEmpleado;
    public javax.swing.JPanel btnAgregarUsuario;
    public javax.swing.JPanel btnCerrarSesion;
    public javax.swing.JPanel btnInformes;
    public javax.swing.JPanel btnIngresoProductos;
    public javax.swing.JPanel btnVenta;
    public javax.swing.JPanel contenedor;
    public javax.swing.JPanel contenedor2;
    private javax.swing.JLabel fondoMenu;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel letAgregarEmpleado;
    // End of variables declaration//GEN-END:variables

    public void setControlador(ControladorMenu controlador){
//        btnIngresoProductos.addActionListener(controlador);
//        btnVenta.addActionListener(controlador);
//        btnActualizacionProductos.addActionListener(controlador);
        this.addWindowListener(controlador);
        btnIngresoProductos.addMouseListener(controlador);
        btnActualizacionProductos.addMouseListener(controlador);
        btnVenta.addMouseListener(controlador);
        btnInformes.addMouseListener(controlador);
        btnAgregarUsuario.addMouseListener(controlador);
        btnCerrarSesion.addMouseListener(controlador);
        btnAgregarEmpleado.addMouseListener(controlador);
        
    }
    
}
